### ISSUE TITLE
Where can I download the lineMod data ?

### ISSUE THREAD

**Issue by bemoregt** [paroj/ObjRecPoseEst#2]
Hi, @paroj 

Where can I download the lineMod data ?

There are so many links  --;

And, I Cannot fine the data link although using finding keyword.

-------------------------------------------------------------
3.) You need my version of the LineMOD data 

Download the data from our project page
https://cvarlab.icg.tugraz.at/projects/3d_object_detection/

**Comment by hironoriyh** [comment]
Hi! I also cannot find the line-mod data as well.

**Comment by paroj** [comment]
that page has been visually upgraded - as a side effect the dataset has been take down.
Please contact one of the original authors for the dataset - and if you are successful post a link here and I will add it to downloads.

**Comment by hironoriyh** [comment]
@paroj  thanks for your info. I will contact to authors. Lemme know if you have recommendation for which author to be contacted. thanks again!

**Comment by paroj** [comment]
https://www.tugraz.at/institute/icg/teams/teamlepetit/research/object-detection-and-3d-pose-estimation/

**Comment by jeasinema** [comment]
Hi, @hironoriyh 

Have you got in touch with the authors? I also cannot find the LINEMOD dataset as well.

**Comment by abinjoabraham** [comment]
Did somebody got any links to the LineMod dataset.

**Comment by Nemokang** [comment]
https://www.tugraz.at/institute/icg/research/team-lepetit/research-projects/object-detection-and-3d-pose-estimation/
this page->data->(ape, benchviseblue, bowl, cam, can, cat, cup, driller, duck, eggbox, glue, holepuncher, iron, lamp, phone, camOrientations.txt, camPositionsElAz.txt)

**Comment by Nemokang** [comment]
@abinjoabraham @jeasinema

**Comment by wadimkehl** [comment]
You should use the new version that has been compiled by Tomas Hodan here: http://cmp.felk.cvut.cz/sixd/challenge_2017/
This link has multiple datasets you can evaluate on and they all come in a standard (SIXD) format that can be read with python scripts from here https://github.com/thodan/sixd_toolkit. We use this version for all evaluations.

**Comment by Daiqy** [comment]
Hello, @paroj , the link of lineMod dataset at the website ([https://www.tugraz.at/institute/icg/research/team-lepetit/research-projects/object-detection-and-3d-pose-estimation/](https://www.tugraz.at/institute/icg/research/team-lepetit/research-projects/object-detection-and-3d-pose-estimation/)) has expired, so we cannot download your dataset. Can you share a new link? Thanks!

**Comment by mariapatni** [comment]
https://github.com/hz-ants/FFB6D

If anyone is curious, in this ReadME, there is a onedrive and google drive link to the LineMOD dataset. this works as of 2025

**Comment by bharathraam29** [comment]
> https://github.com/hz-ants/FFB6D
> 
> If anyone is curious, in this ReadME, there is a onedrive and google drive link to the LineMOD dataset. this works as of 2025

@mariapatni  Thank you so much!! It saved me so much time :)
