### ISSUE TITLE
Error in addNoiseToTrainSeqs

### ISSUE THREAD

**Issue by jpsml** [paroj/ObjRecPoseEst#3]
I'm getting this error:

OpenCV Error: Unsupported format or combination of formats () in cv::medianBlur, file C:\build\2_4_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\smooth.cpp, line 1695
Traceback (most recent call last):
  File "main_train_dagnet.py", line 1515, in <module>
    linemod_train_realandsynth_main(cfgparser)
  File "main_train_dagnet.py", line 1315, in linemod_train_realandsynth_main
    train_set, val_set, macroBatchSize = prepareData(cfg,rng)
  File "main_train_dagnet.py", line 1131, in prepareData
    addNoiseToTrainSeqs(trSeqs,inputMode,rng,addSoftNoise=True,softNoiseRange=0.01,addHardNoise=False,addBgNoise=True)
  File "E:\ObjRecPoseEst-master\src\util\misc.py", line 135, in addNoiseToTrainSeqs
    fractNoise = cv2.medianBlur(fractNoise,3)
cv2.error: C:\build\2_4_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\smooth.cpp:1695: error: (-210)  in function cv::medianBlur

Do you have any idea what this might be?

**Comment by jpsml** [comment]
I've managed to fix this by setting theano.config.floatX to float32, it was set to float64.

**Comment by Nemokang** [comment]
@jpsml Could you please provide some details about how to fix this error? I have met this and don't know how to fix it.

**Comment by Nemokang** [comment]
I don't know where I should change.......
